services:
  auvtt:
    build:
      context: .
      dockerfile: Dockerfile
    image: auvtt:local
    container_name: auvtt
    restart: unless-stopped
    ports:
      - "4321:4321"
      - "8787:8787"
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 4321
      WS_PORT: 8787
    volumes:
      - ./data:/app/data
